# Generated by Django 4.2.7 on 2025-07-17 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("general", "Population générale"),
                            ("elderly", "Personne âgée (+65 ans)"),
                            ("pregnant", "Femme enceinte"),
                            ("child", "Enfant (-12 ans)"),
                            ("chronic", "Malade chronique"),
                            ("outdoor_worker", "Travailleur extérieur"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_lng", models.FloatField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("receive_sms", models.BooleanField(default=True)),
                ("receive_push", models.BooleanField(default=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "Français"), ("wo", "Wolof"), ("ff", "Pulaar")],
                        default="fr",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
