# Generated by Django 4.2.7 on 2025-07-17 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("heat_wave", "Vague de chaleur"),
                            ("extreme_heat", "Chaleur extrême"),
                            ("health_warning", "Alerte sanitaire"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("yellow", "Vigilance jaune"),
                            ("orange", "Vigilance orange"),
                            ("red", "Vigilance rouge"),
                        ],
                        max_length=10,
                    ),
                ),
                ("affected_cities", models.JSONField(default=list)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("general", "Population générale"),
                            ("elderly", "Personne âgée"),
                            ("pregnant", "Femme enceinte"),
                            ("child", "Enfant"),
                            ("chronic", "Malade chronique"),
                            ("outdoor_worker", "Travailleur extérieur"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("yellow", "Jaune"),
                            ("orange", "Orange"),
                            ("red", "Rouge"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("language", models.CharField(default="fr", max_length=10)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="AlertNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_via",
                    models.CharField(
                        choices=[
                            ("push", "Notification push"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alerts.alert"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
