# Generated by Django 4.2.7 on 2025-07-18 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("city", models.CharField(max_length=100)),
                (
                    "symptoms",
                    models.CharField(
                        choices=[
                            ("dehydration", "Déshydratation"),
                            ("heat_exhaustion", "Épuisement thermique"),
                            ("heat_stroke", "Coup de chaleur"),
                            ("breathing_issues", "Difficultés respiratoires"),
                            ("other", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "temperature_felt",
                    models.FloatField(help_text="Température ressentie"),
                ),
                ("has_shade", models.BooleanField(default=False)),
                ("has_water_access", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
