# Generated by Django 4.2.7 on 2025-07-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("temperature", models.FloatField()),
                ("temp_max", models.FloatField()),
                ("temp_min", models.FloatField()),
                ("feels_like", models.FloatField()),
                ("humidity", models.FloatField()),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("green", "Normal"),
                            ("yellow", "Très inconfortable"),
                            ("orange", "Dangereux"),
                            ("red", "Très dangereux"),
                        ],
                        default="green",
                        max_length=10,
                    ),
                ),
                ("source", models.CharField(default="openweathermap", max_length=50)),
                ("recorded_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-recorded_at"],
                "unique_together": {("city", "recorded_at")},
            },
        ),
    ]
