# Generated by Django 5.2.4 on 2025-07-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
